server.port=8083
#config eureka
eureka.client.register.with.eureka=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
#activation de la decouverte dynamique des microservices
eureka.client.fetch-registry=true

# Routes Spring Cloud Gateway Server WebMVC
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=event-service-place-events
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://event-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/places/*/events

spring.cloud.gateway.server.webmvc.routes[2].id=event-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://event-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/events/**

spring.cloud.gateway.server.webmvc.routes[3].id=place-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://place-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/places/**,/api/v1/regions/**,/api/v1/cities/**,/api/v1/districts/**,/api/v1/categories/**
