server.port=${SERVER_PORT:8761}
eureka.instance.hostname=${EUREKA_HOSTNAME:registry-service}
eureka.instance.prefer-ip-address=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
spring.security.user.name=${EUREKA_USERNAME}
spring.security.user.password=${EUREKA_PASSWORD}
# Pour éviter le mode protection en développement
eureka.server.enable-self-preservation=${EUREKA_SELF_PRESERVATION:true}
eureka.server.default-open-for-traffic-count=0
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.eviction-interval-timer-in-ms=${EUREKA_EVICTION_INTERVAL_MS:60000}
management.health.eureka.enabled=true
info.app.description=YeYamo service registry
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=WARN
